name: Deploy RouteMoving

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: 058264368002.dkr.ecr.us-east-1.amazonaws.com
      ECR_REPOSITORY: routemoving
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 \
          -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy container
        run: |
          docker stop routemoving || true
          docker rm routemoving || true

          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker run -d \
            --name routemoving \
            --restart unless-stopped \
            -p 5000:5000 \
            -e AWS_REGION="${{ secrets.AWS_REGION }}" \
            -e AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}" \
            -e SENDER_EMAIL="${{ secrets.SENDER_EMAIL }}" \
            -e RECEIVER_EMAIL="${{ secrets.RECEIVER_EMAIL }}" \
            -e MONGO_URI="${{ secrets.MONGO_URI }}" \
            -e MONGO_DB="${{ secrets.MONGO_DB }}" \
            -e MONGO_COLLECTION="${{ secrets.MONGO_COLLECTION }}" \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Verify deployment
        run: |
          sleep 10
          docker ps
          docker logs routemoving --tail 50
